# Generated by Django 4.1 on 2022-08-23 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturaunt_Day_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('totalNo', models.IntegerField(null=True)),
                ('monthID', models.SmallIntegerField(null=True)),
                ('isActive', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_resturaunt_day_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Guest_Day_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_ResturaunGuestDayMeal', to='baseInfo.department')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Project_ResturaunGuestDayMeal', to='baseInfo.project')),
            ],
            options={
                'db_table': 'tbl_resturaunt_guest_day_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(null=True, upload_to='meal_pix')),
            ],
            options={
                'db_table': 'tbl_resturaunt_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Guest_Day_Meal_Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('resturaunt_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.resturaunt_day_meal')),
                ('resturaunt_guest_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntGuestDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.resturaunt_guest_day_meal')),
            ],
            options={
                'db_table': 'tbl_resturaunt_guest_day_meal_junction',
                'unique_together': {('resturaunt_day_meal', 'resturaunt_guest_day_meal')},
            },
        ),
        migrations.AddField(
            model_name='resturaunt_guest_day_meal',
            name='resturaunt_day_meals',
            field=models.ManyToManyField(through='resturaunt.Resturaunt_Guest_Day_Meal_Junction', to='resturaunt.resturaunt_day_meal'),
        ),
        migrations.CreateModel(
            name='Resturaunt_Employee_Day_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Employee_ResturauntEmployeeDayMeal', to='baseInfo.employee')),
                ('resturaunt_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntDayMeal_ResturauntEmployeeDayMeal', to='resturaunt.resturaunt_day_meal')),
            ],
            options={
                'db_table': 'tbl_resturaunt_employee_day_meal',
            },
        ),
        migrations.AddField(
            model_name='resturaunt_day_meal',
            name='resturaunt_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResturauntMeal_ResturauntDayMeal', to='resturaunt.resturaunt_meal'),
        ),
        migrations.AlterUniqueTogether(
            name='resturaunt_day_meal',
            unique_together={('resturaunt_meal', 'date')},
        ),
    ]
